package com.qianworks.newton.domain;

import lombok.Data;

import java.util.Date;

@Data
public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_privilege.Fid
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_privilege.Fpid
     *
     * @mbggenerated
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_privilege.Fpids
     *
     * @mbggenerated
     */
    private String pids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_privilege.Ftype
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_privilege.Furl
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_privilege.Fpermission
     *
     * @mbggenerated
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_privilege.Fdes
     *
     * @mbggenerated
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_privilege.Fis_leaf
     *
     * @mbggenerated
     */
    private Byte isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_privilege.Fstatus
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_privilege.Fis_deleted
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_privilege.Fcreate_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_privilege.Fmodify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_privilege.Fsequence
     *
     * @mbggenerated
     */
    private Integer sequence;

}