package com.qianworks.newton.dao;

import com.qianworks.newton.domain.User;

public interface UserMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_privilege
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_privilege
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

}